[default]
DEBUG = false
FLASK_ADMIN_NAME = "Academia Backend"
FLASK_ADMIN_SWATCH = 'cerulean'
SQLALCHEMY_DATABASE_URI = 'mysql://admin:B4nc0123@academia-aws.chauks2gy3rg.us-east-1.rds.amazonaws.com/academia'
TITLE = "Academia"
SECRET_KEY = "ficagrandemesmo!"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "academia.ext.database:init_app",
    "academia.ext.configuration:init_app",
    "academia.ext.auth:init_app",
    "academia.blueprints.restapi:init_app",
]


[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.sqlalchemy.SQLAlchemyDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]

[testing]
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://admin:B4nc0123@academia-aws.chauks2gy3rg.us-east-1.rds.amazonaws.com:3306/academia'

[production]
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://admin:B4nc0123@academia-aws.chauks2gy3rg.us-east-1.rds.amazonaws.com:3306/academia'
